export const types = {
    SET_LOADING_ACTION: 'SET_LOADING_ACTION',
    SET_DISHES_ACTION: 'SET_DISHES_ACTION',
    SAVE_DISH_ACTION: 'SAVE_DISH_ACTION',
    DELETE_DISH_ACTION: 'DELETE_DISH_ACTION',
    SEARCH_DISH_ACTION: 'SEARCH_DISH_ACTION'
};