export const types = {
    SET_LOADING_ACTION: 'SET_LOADING_ACTION',
    SET_WAITERS_ACTION: 'GET_WAITERS_ACTION',
    SAVE_WAITER_ACTION: 'SAVE_WAITER_ACTION',
    DELETE_WAITER_ACTION: 'DELETE_WAITER_ACTION',
    SEARCH_WAITER_ACTION: 'SEARCH_WAITER_ACTION'
};