export const types = {
    SET_LOADING_ACTION: 'SET_LOADING_ACTION',
    SET_CHECKS_ACTION: 'SET_CHECKS_ACTION',
    SAVE_CHECK_ACTION: 'SAVE_CHECK_ACTION',
    SEARCH_CHECK_ACTION: 'SEARCH_CHECK_ACTION',
    CLOSE_CHECK_ACTION: 'CLOSE_CHECK_ACTION'
};