export const types = {
    SET_LOADING_ACTION: 'SET_LOADING_ACTION',
    SET_TABLES_ACTION: 'SET_TABLES_ACTION',
    SAVE_TABLE_ACTION: 'SAVE_TABLE_ACTION',
    DELETE_TABLE_ACTION: 'DELETE_TABLE_ACTION',
    SEARCH_TABLE_ACTION: 'SEARCH_TABLE_ACTION'
};